packaging_format = 2

id = "wordpress"
name = "WordPress"
description.en = "Create a beautiful blog or website easily"
description.fr = "Logiciel de création de blog ou de site Web"
description.de = "Hosten Sie ihren Blog oder ihre Webseite"

version = "7.0~ynh1"

maintainers = ["kay0u"]

[upstream]
license = "GPL-2.0"
website = "https://wordpress.org/"
admindoc = "https://codex.wordpress.org/"
code = "https://core.trac.wordpress.org/browser"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "60M"
ram.build = "50M"
ram.runtime = "512M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/blog"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    ask.de = "Wählen Sie die Sprache der Applikation"
    type = "select"
    choices = ["de_DE", "en_US", "es_ES", "fr_FR", "it_IT", "pt_PT", "pt_BR"]
    default = "en_US"

    [install.admin]
    type = "user"

    [install.multisite]
    ask.en = "Enable multisite option?"
    ask.fr = "Activer l'option multisite ?"
    ask.de = "WordPress Multisite aktivieren?"
    type = "boolean"
    default = false

[resources]
        [resources.sources.main]
        url = "https://downloads.wordpress.org/release/wordpress-7.0.zip"
        sha256 = "b2b6827eb7b2b51f4610893e1a6ad02466e76fe0a307bd40ca2a8ba821c40d0b"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:rwx"

    [resources.permissions]
    main.url = "/"
    admin.url = "/wp-login.php"
    admin.additional_urls = ["/wp-admin.php"]
    admin.allowed = "admins"
    admin.show_tile = false

    [resources.apt]
    packages = "mariadb-server, php8.5-mysql, php8.5-curl, php8.5-mbstring, php8.5-xml, php8.5-zip, php8.5-gd, php8.5-soap, php8.5-ssh2, php8.5-tokenizer, php8.5-ldap, php8.5-imagick, php8.5-intl"

    [resources.database]
    type = "mysql"
