#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE DEPENDENCIES
#=================================================

ynh_remove_app_dependencies

#=================================================
# REMOVE THE SQL BDD
#=================================================

ynh_mysql_remove_db $db_name $db_name	# Suppression de la base de donnée et de l'utilisateur associé.

#=================================================
# REMOVE THE MAIN DIR OF THE APP
#=================================================

ynh_secure_remove "/var/www/$app"	# Suppression du dossier de l'application

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================

ynh_remove_nginx_config	# Suppression de la configuration nginx

#=================================================
# REMOVE THE PHP-FPM CONFIGURATION
#=================================================

ynh_remove_fpm_config	# Suppression de la configuration du pool php-fpm

#=================================================
# GENERIC FINALISATION
#=================================================
# REMOVE DEDICATED USER
#=================================================

ynh_system_user_delete $app
